language: node_js
cache: yarn
node_js:
  - node
  - '10'
  - '8'
os:
  - linux
  - osx
branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
script:
  - npm test
after_success:
  - yarn coverage
jobs:
  include:
    - stage: release
      if: branch IN (master, next)
      node_js: node
      script:
        - npx rollup -c
        - npx semantic-release
      env:
        - secure: qnh8WGy9H9unaWYWl6YdJcSDvcN7XaQ1hCxbxIGEaNttoRhBmBL+mwxIiChqMSJYa0M/m7nZFVafbfc6EcHEwUarWG2IGPNKscE36c1iEXtaEfau0OfFk+0fjO0K7MWuhkXHSl2g4IKoV587Bpikdark6JC89OHnJNOLG2a7QtYQQDIM9cVk+U3s1zhuDZ980iJ+4VqJMUy04c9bx6RuSHH6pL+pjxJ7Lg5RKgzfHzpYop+RDLI1la2yoEKip/AKwW2fewZOptSKYOLlxhAcDzZMiWmqswr6uPqEQcVSKB5kEk58j7st25bOAMRE2hdh4Baq5b0qBaQwpEXEKY/h37VGf7+kUe/NZay/bcoWPuoFUCzfpfAag6vFDsS4bqENN10nzALmU9gvVY/o7R66fFR+PDf4lBFz67o94zEtV+r0TWYaIrz9ZCqtmDJ4+vRN0wSUIgnw/oOj5NrCjdOW5Fi6SyJG3He9KtVpK4HAmKCUkuRVBoIlHSeJZjmjmY8Q2Koe4SZmXrahCNRbkBLaIQ+La6tttid1UBo2ZaJznFeueU8mEYabwcRh6PJ8Y8vD2O9YhfTgQ+mvC5DwkX4INpU0OGi7d0JMFsOwniDAAqR1/D/QVBqzTt/HWKXTLnPpOgdNh7pa07nrK50/T79UXymoaHqQvB96DgLvjHWNnVw=
        - secure: J0aRMYmMw5ZzBKs3snK85U2PxyD6mO4XErNNApA5gZknQYv8WlLRtSxNSRMOEPlN16N2ylbK6O2A7Lytw9hV3pRM0YNTzi04/clPGNJxSi3TTKYuZXe8Jw/jOklc4RemUqWQQuDOEne3jOmizDnn0DetqcYBdJHw0ULLlbpFMYj+TBf4iROCd0a6HX2kvF5bypvf5JfZz9jyfkNlgZukMK6hWZFPdVtkAf6wS7wMKwu6TmYYGgiodFYdS9uF6BMsUgjdeHhhGUXBQKpXsmyMYZK/Pt/vffhI+6EguB/lOnPHQMRSsfR4iFAVK7q12P10kCvb9sg+oG3z1v8JN3k5kD6O4znrWu+NXCld+0EFnL+E4YjBstIleRrx1I14cgWtad9C9PWsfiNsx7ItyZ+JeHxtzQ9zDyhzA/+t2/eZbthU1QTA+mZY0yvp+VPyRfBvWPu+R966H9i9y4ycWqN7LvwQHgx4rwqvTQ8wYfgdlrWUtgZEDl2OoofAaKI0NwbGxt9pzQvrtN6yMVxPKC6ALdF8bUbUdfTFZkZgrVWC1CfliMWZ5MVBMhdNKru176/ZFzmTpzv+Oi+JGTbuc9Hps8vJkfFegiRSp28MjfPjSsHAagU4ElaCzg2xBbW1CJi8NASpH4OLqdl0J4Kp8EHhFipJwGeQdGsJeCkuVFxao78=
