name: Check Branch

on: ['pull_request']

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 🛎️
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Size
        run: npm run size
